name: Mirror
on:
  push:
    branches: ['**']
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:planeteyeai-backup/solar-suitability-app.git
          ssh_private_key: ${{ secrets.MIRROR_SSH_KEY }}
